apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: flask-api
          image: mon-api-flask:latest
          ports:
            - containerPort: 5000